[job]
dump_folder = "./outputs/benchmarks/torchtitan_transformer"
description = "Torchtitan llama3 synthetic benchmark (TP/PP/CP)"
print_config = false

[experimental]
custom_import = "benchmarks.torchtitan_transformer.train_spec"

[metrics]
log_freq = 1
disable_color_printing = false
enable_tensorboard = false
enable_wandb = false

[model]
name = "llama3_local"
flavor = "debugmodel"
hf_assets_path = "./torchtitan/tests/assets/tokenizer"

[optimizer]
name = "AdamW"
lr = 8e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 2
decay_ratio = 0.8
decay_type = "linear"
min_lr_factor = 0.0

[training]
dataset = "synthetic"
local_batch_size = 4
seq_len = 2048
max_norm = 1.0
steps = 10

[parallelism]
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 2
enable_async_tensor_parallel = false
pipeline_parallel_degree = 2
pipeline_parallel_schedule = "Interleaved1F1B"
context_parallel_degree = 2

[checkpoint]
enable = false
